CREATE DATABASE IF NOT EXISTS diecast_db CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE diecast_db;
CREATE TABLE IF NOT EXISTS usuarios (id INT AUTO_INCREMENT PRIMARY KEY, usuario VARCHAR(80) NOT NULL UNIQUE, clave VARCHAR(255) NOT NULL, administrador BOOLEAN NOT NULL DEFAULT FALSE);
ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS administrador BOOLEAN NOT NULL DEFAULT FALSE;
CREATE TABLE IF NOT EXISTS diecast (id INT AUTO_INCREMENT PRIMARY KEY, marca VARCHAR(80) NOT NULL, modelo VARCHAR(120) NOT NULL, codigo VARCHAR(50) NOT NULL, anio SMALLINT NOT NULL, numero INT DEFAULT 0, color VARCHAR(60), serie VARCHAR(100), otro VARCHAR(255), thunt VARCHAR(255) NOT NULL DEFAULT '');
ALTER TABLE diecast MODIFY COLUMN thunt VARCHAR(255) NOT NULL DEFAULT '';
INSERT INTO usuarios (usuario, clave, administrador) VALUES ('admin', 'admin123', TRUE) ON DUPLICATE KEY UPDATE administrador=TRUE;
